<a href="https://colab.research.google.com/github/daim-cell/CS5302-GenAI/blob/main/pytorch_basics_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [3]:
t1 = torch.tensor(4.)
t1

tensor(4.)

In [20]:
# the shape outputs (...,x,y). y remains constant is usually the number in a single tensor
t2 = torch.tensor([[[1., 2, 3], [4, 5, 6], [1, 2, 3]],[[1., 2, 3], [4, 5, 6], [1, 2, 3]]])
t2.shape

torch.Size([2, 3, 3])

In [26]:
# prompt: create 3 tensors with requires_grad set to true and show one back propogation

# Create three tensors with requires_grad set to True
t3 = torch.tensor([5.])
t4 = torch.tensor([4.], requires_grad=True)
t5 = torch.tensor([7.], requires_grad=True)

# Perform an operation on the tensors
t6 = t3 * t4 + t5
print(t6)
# Backpropagate through the computation graph
t6.backward()

# Print the gradients of the input tensors

print(t4.grad)
print(t5.grad)


tensor([27.], grad_fn=<AddBackward0>)
tensor([5.])
tensor([1.])


In [31]:
t6_nump = t6.detach().numpy()
print(t6_nump)

torch.from_numpy(t6_nump)

[27.]


tensor([27.])

In [33]:
x = torch.tensor([[1., -1.], [1., 1.]], requires_grad=True)
print(x.pow(2).sum())
out = x.pow(2).sum()
out.backward()
x.grad

tensor(4., grad_fn=<SumBackward0>)


tensor([[ 2., -2.],
        [ 2.,  2.]])

# Logistic Regression


In [91]:

import numpy as np

# using loadtxt()
data = np.loadtxt("/content/sample_data/california_housing_train.csv",
                 delimiter=",", dtype=str)


print(data.shape)
col = data[0]
print(col)
train_data = data[1:,:8]
train_data = train_data.astype(np.float32)
train_target = data[1:,8]
train_target = train_target.astype(np.float32)
print(train_data.shape, train_target.shape)


(17001, 9)
['"longitude"' '"latitude"' '"housing_median_age"' '"total_rooms"'
 '"total_bedrooms"' '"population"' '"households"' '"median_income"'
 '"median_house_value"']
(17000, 8) (17000,)


In [115]:
# The process of gradient descent:
# - Generate predictions
# - Calculate loss
# - Compute gradients w.r.t to weights and biases
# - Adjust weights and biases using gradients proportianal to learning rate
# - Reset gradients

import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import TensorDataset, DataLoader
train = torch.from_numpy(train_data)
target = torch.from_numpy(train_target)

In [113]:
inputs_mean = torch.mean(train, axis=0)
targets_mean = torch.mean(target, axis=0)
train = train / inputs_mean  # Noramalize
target = target / targets_mean

In [ ]:
train_ds = TensorDataset(train, target)
print(train_ds[0:2])
batch = 64

train_loader = DataLoader(train_ds, batch, shuffle = True)

In [123]:
model = nn.Linear(8, 1)
print(model.weight)
print(model.bias)
loss_fn = nn.MSELoss()
optimizer = torch.optim.SGD(model.parameters(), lr=1e-3)


Parameter containing:
tensor([[-0.2139,  0.2435, -0.3249,  0.0629,  0.1824,  0.2738,  0.3247, -0.2508]],
       requires_grad=True)
Parameter containing:
tensor([0.2925], requires_grad=True)


In [125]:
num_epochs = 10
total_step = len(train_loader)
for epoch in range(num_epochs):
    for i, (inputs, labels) in enumerate(train_loader):
        # Reshape images to (batch_size, input_size)
        # Forward pass

        outputs = model(inputs)
        # print(outputs)
        loss = loss_fn(outputs, labels)

        # Backward and optimize
        loss.backward()
        optimizer.step()

        # Reset gradients
        optimizer.zero_grad()


    if (epoch+1) % 10 == 0:
            print ('Epoch [{}/{}], Step [{}/{}], Loss: {:.4f}'
                   .format(epoch+1, num_epochs, i+1, total_step, loss.item()))


Epoch [10/10], Step [266/266], Loss: nan
